apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  namespace: sample
spec:
  selector:
    matchLabels:
      app: sample-app
      type: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
        type: backend
    spec:
      containers:
      - name: sample-app
        image: <ACCOUNT_NAME>.dkr.ecr.<REGION>.amazonaws.com/<ECR_REPO_NAME>:latest
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
    name: sample-app-service
    namespace: sample
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
    selector: 
        app: sample-app
        type: backend
    ports:
    - port: 80
      targetPort: 5000
    loadBalancerSourceRanges:
    - "0.0.0.0/0"
    type: LoadBalancer

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-hpa
  namespace: sample
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-app-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50